### ISSUE TITLE
Using auger with pytest

### ISSUE THREAD

**Issue by JPFrancoia** [laffra/auger#18]
Hi,

This tools seems to be what I'm looking for. Does it work with pytest (instead of unitest) by any chance?

**Comment by NextDesign1** [comment]
Yes, auger works with pytest as well, as pytest has support for unittest.TestCase.

See: https://docs.pytest.org/en/latest/unittest.html

**Comment by JPFrancoia** [comment]
So if I understand well, pytest will automatically convert the tests automatically generated by auger?

**Comment by NextDesign1** [comment]
It does not "convert" them per se, as it does not output a new py file. It simply understands how the unittest module works, and can run them like a standard pytest test case. If you run pytest, it will automatically find and run the tests generated by auger.
