### ISSUE TITLE
Can't generate tests from samples using python 3.6

### ISSUE THREAD

**Issue by mzaglia** [laffra/auger#7]
I'm trying to run the samples and when using python 3.6 the tests aren't generated, only with python 2.7.
OS: Ubuntu 18.04
pip freeze: 
auger-python==0.1.29
funcsigs==1.0.2
mock==2.0.0
pbr==5.0.0
six==1.11.0

**Comment by laffra** [comment]
Can you please try again with v0.1.31 or HEAD? I just added improvements that should handle the difference between reflection APIs in 2.7 and 3.6 much better.
